import type { TeamBoardFixture, TeamOption } from './type';

export const TEAM_OPTIONS = [
  { label: 'Platform', value: 'Platform' },
  { label: 'Agent Runtime', value: 'Agent Runtime' },
  { label: 'Delivery Governance', value: 'Delivery Governance' },
] satisfies TeamOption[];

export const TEAM_FIXTURES = [
  {
    name: 'Platform',
    summary: '聚焦平台体验、核心能力与跨团队交付节奏。',
    metrics: [
      {
        key: 'completion-rate',
        title: '迭代完成率',
        value: '86%',
        description: '高于本期 85% 目标',
        tone: 'success',
      },
      {
        key: 'weekly-throughput',
        title: '本周吞吐',
        value: 42,
        description: '较上周增加 6 项',
        tone: 'brand',
      },
      {
        key: 'work-in-progress',
        title: '进行中',
        value: 12,
        description: '覆盖 4 个交付流',
        tone: 'info',
      },
      {
        key: 'blockers',
        title: '阻塞项',
        value: 2,
        description: '均已明确协同 Owner',
        tone: 'warning',
      },
    ],
    throughput: [
      { key: 'mon', label: '周一', value: 4, valueLabel: '4 项' },
      { key: 'tue', label: '周二', value: 5, valueLabel: '5 项' },
      { key: 'wed', label: '周三', value: 6, valueLabel: '6 项' },
      { key: 'thu', label: '周四', value: 7, valueLabel: '7 项' },
      { key: 'fri', label: '周五', value: 5, valueLabel: '5 项' },
      { key: 'sat', label: '周六', value: 8, valueLabel: '8 项' },
      {
        key: 'sun',
        label: '周日',
        value: 7,
        valueLabel: '7 项',
        tone: 'success',
      },
    ],
    distribution: [
      { key: 'planned', label: '规划中', value: 12, tone: 'neutral' },
      { key: 'ready', label: '就绪', value: 18, tone: 'info' },
      { key: 'active', label: '开发中', value: 24, tone: 'brand' },
      { key: 'review', label: '评审中', value: 16, tone: 'warning' },
      { key: 'done', label: '已交付', value: 30, tone: 'success' },
    ],
    members: [
      { key: 'lin-cheng', name: '林澄', role: '平台体验负责人', load: 72 },
      { key: 'zhou-yao', name: '周遥', role: '前端工程师', load: 64 },
      { key: 'chen-mo', name: '陈默', role: '平台后端工程师', load: 81 },
    ],
    blockers: [
      {
        key: 'artifact-permissions',
        title: '制品权限矩阵待确认',
        description: '需要 Security Owner 确认跨 Workspace 的只读范围。',
        status: '待协同',
        tone: 'warning',
      },
      {
        key: 'design-token-alignment',
        title: '暗色主题验收窗口未确定',
        description: '已准备验收清单，等待设计团队确认时间。',
        status: '排期中',
        tone: 'info',
      },
    ],
  },
  {
    name: 'Agent Runtime',
    summary: '聚焦 Agent Attempt 稳定性、运行时效率与执行可观测性。',
    metrics: [
      {
        key: 'success-rate',
        title: '运行成功率',
        value: '94%',
        description: '连续三日保持在 92% 以上',
        tone: 'success',
      },
      {
        key: 'weekly-attempts',
        title: '本周尝试',
        value: 68,
        description: '覆盖 11 类 Workflow',
        tone: 'brand',
      },
      {
        key: 'active-runs',
        title: '运行中',
        value: 9,
        description: '当前无超时 Attempt',
        tone: 'info',
      },
      {
        key: 'blockers',
        title: '阻塞项',
        value: 1,
        description: '运行时团队正在排查',
        tone: 'warning',
      },
    ],
    throughput: [
      { key: 'mon', label: '周一', value: 8, valueLabel: '8 次' },
      { key: 'tue', label: '周二', value: 9, valueLabel: '9 次' },
      { key: 'wed', label: '周三', value: 10, valueLabel: '10 次' },
      { key: 'thu', label: '周四', value: 11, valueLabel: '11 次' },
      { key: 'fri', label: '周五', value: 9, valueLabel: '9 次' },
      { key: 'sat', label: '周六', value: 12, valueLabel: '12 次' },
      {
        key: 'sun',
        label: '周日',
        value: 9,
        valueLabel: '9 次',
        tone: 'success',
      },
    ],
    distribution: [
      { key: 'queued', label: '排队中', value: 8, tone: 'neutral' },
      { key: 'preparing', label: '准备中', value: 14, tone: 'info' },
      { key: 'running', label: '运行中', value: 28, tone: 'brand' },
      { key: 'verifying', label: '验证中', value: 20, tone: 'warning' },
      { key: 'finished', label: '已完成', value: 30, tone: 'success' },
    ],
    members: [
      { key: 'fang-zhou', name: '方舟', role: 'Agent 平台工程师', load: 84 },
      { key: 'xu-nuo', name: '许诺', role: '运行时工程师', load: 69 },
      { key: 'he-chuan', name: '贺川', role: '可观测性工程师', load: 62 },
    ],
    blockers: [
      {
        key: 'sandbox-cold-start',
        title: '沙箱镜像冷启动偏高',
        description: 'P95 超过目标 18 秒，正在核对镜像层缓存。',
        status: '排查中',
        tone: 'warning',
      },
    ],
  },
  {
    name: 'Delivery Governance',
    summary: '聚焦 Merge Request、发布 Gate 与交付证据的闭环质量。',
    metrics: [
      {
        key: 'merge-pass-rate',
        title: '合并通过率',
        value: '91%',
        description: '较上周提升 4 个百分点',
        tone: 'success',
      },
      {
        key: 'weekly-deliveries',
        title: '本周交付',
        value: 31,
        description: '覆盖 7 个 Repository',
        tone: 'brand',
      },
      {
        key: 'pending-reviews',
        title: '待评审',
        value: 7,
        description: '最久等待 5 小时',
        tone: 'info',
      },
      {
        key: 'blockers',
        title: '阻塞项',
        value: 3,
        description: '其中 1 项需要跨团队处理',
        tone: 'danger',
      },
    ],
    throughput: [
      { key: 'mon', label: '周一', value: 3, valueLabel: '3 项' },
      { key: 'tue', label: '周二', value: 4, valueLabel: '4 项' },
      { key: 'wed', label: '周三', value: 5, valueLabel: '5 项' },
      { key: 'thu', label: '周四', value: 6, valueLabel: '6 项' },
      { key: 'fri', label: '周五', value: 4, valueLabel: '4 项' },
      { key: 'sat', label: '周六', value: 5, valueLabel: '5 项' },
      {
        key: 'sun',
        label: '周日',
        value: 4,
        valueLabel: '4 项',
        tone: 'success',
      },
    ],
    distribution: [
      { key: 'draft', label: '草拟中', value: 10, tone: 'neutral' },
      { key: 'review', label: '评审中', value: 16, tone: 'info' },
      { key: 'checking', label: '检查中', value: 22, tone: 'brand' },
      { key: 'gated', label: 'Gate 中', value: 24, tone: 'warning' },
      { key: 'released', label: '已发布', value: 28, tone: 'success' },
    ],
    members: [
      { key: 'shen-yi', name: '沈一', role: '交付治理负责人', load: 76 },
      { key: 'tang-ning', name: '唐宁', role: '发布工程师', load: 71 },
      { key: 'luo-qing', name: '罗晴', role: '合规工程师', load: 67 },
    ],
    blockers: [
      {
        key: 'gate-evidence',
        title: '发布 Gate 证据缺失',
        description: '一个 Repository 尚未上传供应链签名证据。',
        status: '需补充',
        tone: 'danger',
      },
      {
        key: 'review-capacity',
        title: '安全评审容量不足',
        description: '两项高风险变更集中在同一发布窗口。',
        status: '待协调',
        tone: 'warning',
      },
      {
        key: 'release-window',
        title: '发布窗口冲突',
        description: '基础设施维护与一项业务发布存在重叠。',
        status: '确认中',
        tone: 'info',
      },
    ],
  },
] as const satisfies readonly TeamBoardFixture[];
