import { createStyles } from 'antd-style';

export const useStyles = createStyles(({ token }) => ({
  masterDetail: {
    display: 'flex',
    gap: token.margin,
    alignItems: 'flex-start',
  },
  selectorCard: {
    display: 'flex',
    flex: '0 0 236px',
    flexDirection: 'column',
    gap: token.marginXS,
  },
  selectorHeader: {
    display: 'flex',
    gap: token.marginXXS,
    alignItems: 'baseline',
    marginBlockEnd: token.marginSM,
    paddingInline: token.paddingXXS,
  },
  selectorTitle: {
    margin: 0,
    color: token.colorText,
    fontSize: token.fontSize,
    fontWeight: token.fontWeightStrong,
  },
  secondaryText: {
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  workspaceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.marginXS,
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  workspaceButton: {
    width: '100%',
    height: 'auto',
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    textAlign: 'start',
    whiteSpace: 'normal',

    '&:hover': {
      borderColor: token.colorPrimaryBorder,
      background: token.colorPrimaryBg,
    },

    '&:focus-visible': {
      outline: `${token.lineWidthFocus}px solid ${token.colorPrimaryBorder}`,
      outlineOffset: token.marginXXS,
    },
  },
  workspaceButtonActive: {
    borderColor: token.colorPrimary,
    background: token.colorPrimaryBg,
  },
  workspaceTitleRow: {
    display: 'flex',
    gap: token.marginXS,
    alignItems: 'center',
  },
  workspaceTeamDot: {
    width: token.controlHeightXS / 2,
    height: token.controlHeightXS / 2,
    flex: '0 0 auto',
    borderRadius: '50%',
    background: token.colorPrimary,
  },
  workspaceName: {
    flex: 1,
    minWidth: 0,
    color: token.colorText,
    fontWeight: token.fontWeightStrong,
  },
  workspaceMeta: {
    display: 'block',
    marginBlockStart: token.marginXXS,
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  selectorNote: {
    margin: 0,
    paddingInline: token.paddingXXS,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
    lineHeight: token.lineHeightSM,
  },
  detailCard: {
    flex: 1,
    minWidth: 0,
  },
  detailSurface: {
    overflow: 'hidden',
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  detailHeader: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    padding: `${token.paddingSM}px ${token.padding}px`,
    borderBlockEnd: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
  },
  detailAvatar: {
    display: 'inline-flex',
    width: 38,
    height: 38,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: token.borderRadiusLG,
    background: token.colorPrimary,
    color: token.colorTextLightSolid,
    fontSize: token.fontSizeLG,
    fontWeight: token.fontWeightStrong,
  },
  detailIdentity: {
    minWidth: 0,
  },
  detailTitle: {
    margin: 0,
    color: token.colorText,
    fontSize: token.fontSizeHeading3,
    lineHeight: token.lineHeightHeading3,
  },
  detailDescription: {
    margin: 0,
    color: token.colorTextSecondary,
  },
  panel: {
    minHeight: 360,
    padding: `${token.paddingSM}px ${token.padding}px ${token.padding}px`,
  },
  panelHeader: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBlockEnd: token.marginSM,
  },
  panelTitle: {
    margin: `0 0 ${token.marginSM}px`,
    color: token.colorText,
    fontSize: token.fontSizeLG,
    fontWeight: token.fontWeightStrong,
  },
  memberList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(280px, 1fr))',
    gap: token.marginSM,
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  memberItem: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    minWidth: 0,
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  memberAvatar: {
    display: 'inline-flex',
    width: 34,
    height: 34,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: token.borderRadiusLG,
    background: token.colorFillSecondary,
    color: token.colorText,
    fontWeight: token.fontWeightStrong,
  },
  memberBody: {
    display: 'flex',
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    gap: token.marginXXS,
  },
  memberIdentity: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: token.marginXS,
    alignItems: 'center',
  },
  memberName: {
    color: token.colorText,
    fontWeight: token.fontWeightStrong,
  },
  code: {
    color: token.colorTextSecondary,
    fontFamily: token.fontFamilyCode,
    fontSize: token.fontSizeSM,
  },
  connectionCard: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    marginBlockEnd: token.marginSM,
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorFillQuaternary,
  },
  gitLabMark: {
    fontSize: token.fontSizeHeading2,
    lineHeight: 1,
  },
  connectionBody: {
    display: 'flex',
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    gap: token.marginXXS,
  },
  connectionTitle: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: token.marginXS,
    alignItems: 'center',
    color: token.colorText,
    fontWeight: token.fontWeightStrong,
  },
  repositorySummary: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBlockEnd: token.marginSM,
  },
  selectedCount: {
    flexShrink: 0,
    color: token.colorPrimary,
  },
  repositoryList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(240px, 1fr))',
    gap: token.marginXS,
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  repositoryItem: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    minWidth: 0,
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
  },
  repositoryName: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    color: token.colorText,
    fontFamily: token.fontFamilyCode,
    fontWeight: token.fontWeightStrong,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  repositoryNote: {
    margin: `${token.marginSM}px 0 0`,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
  settingsForm: {
    maxWidth: 520,
  },
  settingsLabel: {
    display: 'block',
    marginBlockEnd: token.marginXXS,
    color: token.colorText,
    fontWeight: token.fontWeightStrong,
  },
  settingsNameRow: {
    display: 'flex',
    gap: token.marginXS,
  },
  archiveCard: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    justifyContent: 'space-between',
    maxWidth: 520,
    marginBlockStart: token.marginXL,
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorErrorBorder}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorErrorBg,
  },
  archiveTitle: {
    display: 'block',
    color: token.colorText,
  },
  archiveDescription: {
    display: 'block',
    marginBlockStart: token.marginXXS,
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  visuallyHidden: {
    position: 'absolute',
    width: 1,
    height: 1,
    overflow: 'hidden',
    clip: 'rect(0 0 0 0)',
    whiteSpace: 'nowrap',
    clipPath: 'inset(50%)',
  },
}));
