import { createStyles } from 'antd-style';

export const useStyles = createStyles(({ token }) => ({
  page: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.margin,
  },
  metricsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: token.margin,
  },
  masterDetail: {
    display: 'grid',
    gridTemplateColumns: '260px minmax(0, 1fr)',
    gap: token.margin,
    alignItems: 'start',
  },
  card: {
    borderColor: token.colorBorderSecondary,
    boxShadow: token.boxShadowTertiary,
  },
  selectorHeader: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.marginXXS,
    marginBlockEnd: token.marginSM,
  },
  selectorTitle: {
    margin: 0,
    color: token.colorText,
    fontSize: token.fontSizeLG,
    fontWeight: token.fontWeightStrong,
  },
  secondaryText: {
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  workspaceList: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.marginXS,
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  workspaceButton: {
    width: '100%',
    height: 'auto',
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    textAlign: 'start',
    whiteSpace: 'normal',

    '&:hover': {
      borderColor: token.colorPrimaryBorder,
      background: token.colorPrimaryBg,
    },

    '&:focus-visible': {
      outline: `${token.lineWidthFocus}px solid ${token.colorPrimaryBorder}`,
      outlineOffset: token.marginXXS,
    },
  },
  workspaceButtonActive: {
    borderColor: token.colorPrimary,
    background: token.colorPrimaryBg,
  },
  workspaceTitleRow: {
    display: 'flex',
    gap: token.marginXS,
    alignItems: 'center',
  },
  workspaceName: {
    flex: 1,
    minWidth: 0,
    color: token.colorText,
    fontWeight: token.fontWeightStrong,
  },
  workspaceMeta: {
    display: 'block',
    marginBlockStart: token.marginXXS,
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  workspaceDescription: {
    display: 'block',
    marginBlockStart: token.marginXXS,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
    lineHeight: token.lineHeightSM,
  },
  detailHeader: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'flex-start',
    justifyContent: 'space-between',
    marginBlockEnd: token.marginXS,
  },
  detailTitle: {
    margin: 0,
    color: token.colorText,
    fontSize: token.fontSizeHeading3,
    lineHeight: token.lineHeightHeading3,
  },
  detailDescription: {
    margin: 0,
    color: token.colorTextSecondary,
  },
  panel: {
    minHeight: 360,
    paddingBlock: token.paddingSM,
  },
  panelHeader: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBlockEnd: token.marginSM,
  },
  panelTitle: {
    margin: 0,
    color: token.colorText,
    fontSize: token.fontSizeLG,
    fontWeight: token.fontWeightStrong,
  },
  memberList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: token.marginSM,
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  memberItem: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    minWidth: 0,
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  memberAvatar: {
    display: 'inline-flex',
    width: 34,
    height: 34,
    flexShrink: 0,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: token.borderRadiusLG,
    background: token.colorFillSecondary,
    color: token.colorText,
    fontWeight: token.fontWeightStrong,
  },
  memberBody: {
    display: 'flex',
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    gap: token.marginXXS,
  },
  memberIdentity: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: token.marginXS,
    alignItems: 'center',
  },
  memberName: {
    color: token.colorText,
    fontWeight: token.fontWeightStrong,
  },
  code: {
    color: token.colorTextSecondary,
    fontFamily: token.fontFamilyCode,
    fontSize: token.fontSizeSM,
  },
  repositoryList: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: token.marginSM,
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  repositoryItem: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
  },
  repositoryBody: {
    display: 'flex',
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    gap: token.marginXXS,
  },
  repositoryName: {
    overflow: 'hidden',
    color: token.colorText,
    fontFamily: token.fontFamilyCode,
    fontWeight: token.fontWeightStrong,
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  branch: {
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  settingsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(2, minmax(0, 1fr))',
    gap: token.margin,
  },
  settingsSection: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: token.marginSM,
    padding: token.padding,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  settingsHeading: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsTitle: {
    margin: 0,
    color: token.colorText,
    fontSize: token.fontSizeLG,
    fontWeight: token.fontWeightStrong,
  },
  keyValueList: {
    display: 'grid',
    gridTemplateColumns: 'max-content minmax(0, 1fr)',
    gap: `${token.marginXS}px ${token.marginSM}px`,
    margin: 0,
  },
  key: {
    color: token.colorTextTertiary,
  },
  value: {
    minWidth: 0,
    margin: 0,
    overflowWrap: 'anywhere',
    color: token.colorTextSecondary,
  },
  policyList: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.marginXS,
    margin: 0,
    paddingInlineStart: token.paddingLG,
    color: token.colorTextSecondary,
  },
  settingsActions: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: token.marginXS,
    marginBlockStart: 'auto',
  },
}));
