export const APP_PATHS = {
  home: '/home',
  tasks: '/tasks',
  workspaces: '/workspaces',
  messages: '/messages',
  teamBoard: '/team-board',
  audit: '/audit',
  admin: '/admin',
  adminOrganization: '/admin/organization',
  adminWorkspaces: '/admin/workspaces',
  adminSkills: '/admin/skills',
  adminModels: '/admin/models',
  adminRoles: '/admin/roles',
  adminUsers: '/admin/users',
  adminGrants: '/admin/grants',
  adminPolicies: '/admin/policies',
  adminMenus: '/admin/menus',
} as const;
