export default [
  { path: '/login', component: './Login', layout: false },
  { path: '/bootstrap', component: './Bootstrap', layout: false },
  {
    path: '/',
    wrappers: ['@/features/auth/RouteGuard'],
    routes: [
      { path: '/', redirect: '/home' },
      { name: '工作台', path: '/home', component: './Home' },
      { name: '任务', path: '/tasks', component: './Tasks' },
      {
        name: '归档任务',
        path: '/tasks/archived',
        component: './Tasks/Archived',
        hideInMenu: true,
        parentKeys: ['/tasks'],
      },
      {
        name: '任务详情',
        path: '/tasks/:taskId',
        component: './TaskDetail',
        hideInMenu: true,
        parentKeys: ['/tasks'],
      },
      { name: '工作区', path: '/workspaces', component: './Workspaces' },
      { name: '消息中心', path: '/messages', component: './Messages' },
      { name: '团队看板', path: '/team-board', component: './TeamBoard' },
      { name: '审计看板', path: '/audit', component: './Audit' },
      {
        name: '管理概览',
        path: '/admin',
        component: './Admin',
        access: 'canAccessAdmin',
      },
      {
        name: '工作区管理',
        path: '/admin/workspaces',
        component: './AdminWorkspaces',
        access: 'canAccessAdmin',
      },
      {
        name: '技能管理',
        path: '/admin/skills',
        component: './AdminSkills',
        access: 'canAccessAdmin',
      },
      {
        name: '模型管理',
        path: '/admin/models',
        component: './AdminModels',
        access: 'canAccessAdmin',
      },
      {
        name: '角色管理',
        path: '/admin/roles',
        component: './AdminRoles',
        access: 'canAccessAdmin',
      },
      {
        name: '用户管理',
        path: '/admin/users',
        component: './AdminUsers',
        access: 'canAccessAdmin',
      },
      {
        name: '菜单管理',
        path: '/admin/menus',
        component: './AdminMenus',
        access: 'canAccessAdmin',
      },
    ],
  },
];
