export default [
  { path: '/login', component: './Login', layout: false, routeKey: 'login' },
  {
    path: '/bootstrap',
    component: './Bootstrap',
    layout: false,
    routeKey: 'bootstrap',
  },
  {
    path: '/',
    routeKey: 'app',
    wrappers: ['@/features/navigation/RouteGuard'],
    routes: [
      { path: '/', redirect: '/home', routeKey: 'root' },
      {
        name: '工作台',
        path: '/home',
        component: './Home',
        routeKey: 'home',
      },
      {
        name: '任务',
        path: '/tasks',
        component: './Tasks',
        routeKey: 'tasks',
      },
      {
        name: '归档任务',
        path: '/tasks/archived',
        component: './Tasks/Archived',
        hideInMenu: true,
        parentKeys: ['/tasks'],
        routeKey: 'tasks.archived',
      },
      {
        name: '任务详情',
        path: '/tasks/:taskId',
        component: './TaskDetail',
        hideInMenu: true,
        parentKeys: ['/tasks'],
        routeKey: 'tasks.detail',
      },
      {
        name: '工作区',
        path: '/workspaces',
        component: './Workspaces',
        routeKey: 'workspaces',
      },
      {
        name: '消息中心',
        path: '/messages',
        component: './Messages',
        routeKey: 'messages',
      },
      {
        name: '团队看板',
        path: '/team-board',
        component: './TeamBoard',
        routeKey: 'team-board',
      },
      {
        name: '审计看板',
        path: '/audit',
        component: './Audit',
        routeKey: 'audit',
      },
      {
        name: '管理概览',
        path: '/admin',
        component: './Admin',
        routeKey: 'admin',
      },
      {
        name: '工作区管理',
        path: '/admin/workspaces',
        component: './AdminWorkspaces',
        routeKey: 'admin.workspaces',
      },
      {
        name: '组织管理',
        path: '/admin/organization',
        component: './AdminOrganization',
        routeKey: 'admin.organization',
      },
      {
        name: '技能管理',
        path: '/admin/skills',
        component: './AdminSkills',
        routeKey: 'admin.skills',
      },
      {
        name: '模型管理',
        path: '/admin/models',
        component: './AdminModels',
        routeKey: 'admin.models',
      },
      {
        name: '角色管理',
        path: '/admin/roles',
        component: './AdminRoles',
        routeKey: 'admin.roles',
      },
      {
        name: '用户管理',
        path: '/admin/users',
        component: './AdminUsers',
        routeKey: 'admin.users',
      },
      {
        name: 'Grant 管理',
        path: '/admin/grants',
        component: './AdminGrants',
        routeKey: 'admin.grants',
      },
      {
        name: '菜单管理',
        path: '/admin/menus',
        component: './AdminMenus',
        routeKey: 'admin.menus',
      },
    ],
  },
];
