import type { SkillItem } from './type';

export const SKILL_ITEMS: readonly SkillItem[] = Object.freeze([
  Object.freeze({
    key: 'superpowers',
    name: 'superpowers',
    version: 'v5.0',
    stack: '通用 · spec → plan → dev → test → review',
    content: '通过阶段化工作流约束需求、计划、实现、测试与评审。',
    status: 'active',
    type: 'SDD 方法',
    usage: '214 任务',
  }),
  Object.freeze({
    key: 'grill-me',
    name: 'grill-me',
    version: 'v3.2',
    stack: '通用 · 追问对齐 → spec → dev → review',
    content: '通过连续追问收敛需求边界并形成可验证规格。',
    status: 'active',
    type: 'SDD 方法',
    usage: '186 任务',
  }),
  Object.freeze({
    key: 'frontend-react',
    name: '前端开发规范 (React)',
    version: 'v2.8',
    stack: 'React 18 / TypeScript',
    content: '约束 React 与 TypeScript 仓库的组件、测试和交付质量。',
    status: 'active',
    type: '仓库规范',
    usage: '96 仓库',
  }),
  Object.freeze({
    key: 'frontend-vue',
    name: '前端开发规范 (Vue)',
    version: 'v2.3',
    stack: 'Vue 3',
    content: '约束 Vue 仓库的组件组织、状态管理与交付质量。',
    status: 'active',
    type: '仓库规范',
    usage: '41 仓库',
  }),
  Object.freeze({
    key: 'frontend-rn',
    name: '前端开发规范 (RN)',
    version: 'v1.9',
    stack: 'React Native',
    content: '约束 React Native 应用的跨端实现与交付质量。',
    status: 'active',
    type: '仓库规范',
    usage: '18 仓库',
  }),
  Object.freeze({
    key: 'mini-program',
    name: '小程序开发规范',
    version: 'v1.6',
    stack: '原生小程序',
    content: '约束原生小程序的页面、组件与发布流程。',
    status: 'active',
    type: '仓库规范',
    usage: '22 仓库',
  }),
  Object.freeze({
    key: 'uniapp',
    name: 'uniapp 开发规范',
    version: 'v1.2',
    stack: 'uniapp',
    content: '约束 uniapp 项目的跨端实现与发布流程。',
    status: 'inactive',
    type: '仓库规范',
    usage: '6 仓库',
  }),
  Object.freeze({
    key: 'backend-java',
    name: '后端开发规范 (Java)',
    version: 'v3.1',
    stack: 'Java / Spring',
    content: '约束 Java 与 Spring 服务的接口、测试和交付质量。',
    status: 'active',
    type: '仓库规范',
    usage: '118 仓库',
  }),
  Object.freeze({
    key: 'pr-review-bot',
    name: 'PR 机器人审核',
    version: 'v4.0',
    stack: '全部仓库 · MR 前置',
    content: '在 MR 合并前执行平台默认的自动化代码审查。',
    status: 'active',
    type: '平台默认',
    usage: '全平台',
    locked: true,
  }),
]);

export const SKILL_STATUS_META = {
  active: { label: '启用', tone: 'success' },
  inactive: { label: '禁用', tone: 'neutral' },
} as const;

export const SKILL_TYPE_META = {
  'SDD 方法': { label: 'SDD 方法', tone: 'purple' },
  仓库规范: { label: '仓库规范', tone: 'info' },
  平台默认: { label: '平台默认', tone: 'neutral' },
} as const;
