import { createStyles } from 'antd-style';

export const useStyles = createStyles(({ token }) => ({
  page: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.margin,
  },
  toolbar: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  masterDetail: {
    display: 'flex',
    gap: token.margin,
    alignItems: 'flex-start',
  },
  catalog: {
    width: 248,
    flex: '0 0 248px',
    overflow: 'hidden',
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  catalogGroup: {
    display: 'flex',
    flexDirection: 'column',
  },
  catalogGroupHeader: {
    display: 'flex',
    gap: token.marginXS,
    alignItems: 'baseline',
    padding: `${token.paddingXS}px ${token.paddingSM}px`,
    borderBlockEnd: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    background: token.colorFillQuaternary,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
  catalogList: {
    margin: 0,
    padding: 0,
    listStyle: 'none',
  },
  catalogButton: {
    display: 'flex',
    width: '100%',
    height: 'auto',
    gap: token.marginXS,
    alignItems: 'center',
    justifyContent: 'flex-start',
    padding: `${token.paddingXS}px ${token.paddingSM}px`,
    borderInlineStart: `${token.lineWidthBold}px solid transparent`,
    borderRadius: 0,
    textAlign: 'start',
  },
  catalogButtonActive: {
    borderInlineStartColor: token.colorPrimary,
    background: token.colorPrimaryBg,
  },
  statusDot: {
    width: 7,
    height: 7,
    flex: '0 0 auto',
    borderRadius: '50%',
    background: token.colorFill,
  },
  statusDotActive: {
    background: token.colorSuccess,
  },
  catalogName: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
  },
  code: {
    color: token.colorTextSecondary,
    fontFamily: token.fontFamilyCode,
    fontSize: token.fontSizeSM,
  },
  detail: {
    display: 'flex',
    flex: 1,
    minWidth: 0,
    flexDirection: 'column',
    gap: token.margin,
  },
  detailHeader: {
    padding: token.padding,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  detailTitleRow: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: token.marginXS,
    alignItems: 'center',
  },
  detailTitle: {
    margin: 0,
    color: token.colorText,
    fontSize: token.fontSizeHeading4,
    lineHeight: token.lineHeightHeading4,
  },
  protectedBadge: {
    display: 'inline-flex',
    gap: token.marginXXS,
    alignItems: 'center',
    padding: `0 ${token.paddingXS}px`,
    borderRadius: token.borderRadiusSM,
    background: token.colorWarningBg,
    color: token.colorWarning,
    fontSize: token.fontSizeSM,
  },
  detailActions: {
    display: 'flex',
    gap: token.marginXS,
    marginInlineStart: 'auto',
  },
  detailMeta: {
    margin: `${token.marginXS}px 0 0`,
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  contentGrid: {
    display: 'flex',
    gap: token.margin,
    alignItems: 'flex-start',
  },
  sourceCard: {
    flex: 1,
    minWidth: 0,
    overflow: 'hidden',
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  cardHeader: {
    display: 'flex',
    gap: token.marginXS,
    alignItems: 'baseline',
    justifyContent: 'space-between',
    padding: `${token.paddingXS}px ${token.padding}px`,
    borderBlockEnd: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
  },
  cardTitle: {
    margin: 0,
    color: token.colorText,
    fontSize: token.fontSize,
    fontWeight: token.fontWeightStrong,
  },
  skillSource: {
    maxHeight: 'calc(100vh - 330px)',
    margin: 0,
    overflowY: 'auto',
    padding: `${token.paddingSM}px ${token.padding}px`,
    color: token.colorText,
    fontFamily: token.fontFamilyCode,
    fontSize: token.fontSizeSM,
    lineHeight: 1.8,
    whiteSpace: 'pre-wrap',
  },
  historyCard: {
    width: 272,
    flex: '0 0 272px',
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorBgContainer,
  },
  historyList: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.marginSM,
    margin: `${token.marginSM}px 0 0`,
    padding: 0,
    listStyle: 'none',
  },
  historyItem: {
    display: 'flex',
    gap: token.marginXS,
    alignItems: 'flex-start',
  },
  historyDot: {
    width: 7,
    height: 7,
    flex: '0 0 auto',
    marginBlockStart: token.marginXXS,
    borderRadius: '50%',
    background: token.colorPrimary,
  },
  historyNote: {
    display: 'block',
    marginBlockStart: token.marginXXS,
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  historyMeta: {
    display: 'block',
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
  creationGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(3, minmax(0, 1fr))',
    gap: token.marginSM,
  },
  creationOption: {
    display: 'flex',
    height: 'auto',
    minHeight: 132,
    flexDirection: 'column',
    gap: token.marginXS,
    alignItems: 'flex-start',
    justifyContent: 'flex-start',
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    color: token.colorText,
    textAlign: 'start',
    whiteSpace: 'normal',
    '&:hover': {
      borderColor: token.colorPrimary,
      background: token.colorPrimaryBg,
    },
  },
  creationOptionContent: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.marginXS,
    alignItems: 'flex-start',
    '& strong': {
      fontSize: token.fontSize,
    },
  },
  creationDescription: {
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
    lineHeight: token.lineHeightSM,
  },
  creationIcon: {
    display: 'inline-flex',
    width: 32,
    height: 32,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: token.borderRadius,
    background: token.colorPrimaryBg,
    color: token.colorPrimary,
    fontSize: token.fontSizeLG,
  },
  createFlow: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.marginSM,
  },
  createHint: {
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  createFooter: {
    display: 'flex',
    gap: token.marginSM,
    justifyContent: 'flex-end',
  },
  chatDraft: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.marginXS,
    padding: token.paddingSM,
    border: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorFillQuaternary,
  },
  chatDraftDetails: {
    display: 'grid',
    gridTemplateColumns: '64px minmax(0, 1fr)',
    gap: `${token.marginXS}px ${token.marginSM}px`,
    margin: 0,
    fontSize: token.fontSizeSM,
    '& dt': {
      color: token.colorTextTertiary,
    },
    '& dd': {
      margin: 0,
      color: token.colorText,
    },
  },
  chatDraftSummary: {
    margin: 0,
    paddingBlockStart: token.paddingXS,
    borderBlockStart: `${token.lineWidth}px ${token.lineType} ${token.colorBorderSecondary}`,
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
    lineHeight: token.lineHeight,
  },
  zipFileCard: {
    display: 'flex',
    gap: token.marginSM,
    alignItems: 'center',
    padding: token.paddingSM,
    border: `${token.lineWidthBold}px dashed ${token.colorPrimary}`,
    borderRadius: token.borderRadiusLG,
    background: token.colorPrimaryBg,
  },
  zipFileMeta: {
    display: 'flex',
    minWidth: 0,
    flexDirection: 'column',
    gap: token.marginXXS,
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  zipSteps: {
    display: 'flex',
    flexDirection: 'column',
    gap: token.marginXS,
    margin: 0,
    paddingInlineStart: token.paddingLG,
    color: token.colorTextSecondary,
    fontSize: token.fontSizeSM,
  },
  staticNotice: {
    margin: 0,
    color: token.colorTextTertiary,
    fontSize: token.fontSizeSM,
  },
}));
